### ISSUE TITLE
Add instructions on how to enable the class

### ISSUE THREAD

**Issue by Navideck-fotis** [mapbox/Fingertips#18]
In AppDelegate.m import the following class:
#import <Fingertips/MBFingerTipWindow.h>

Add the following method:
//Used for showing touches
- (MBFingerTipWindow *)window
{
    static MBFingerTipWindow *visualFeedbackWindow = nil;
    if (!visualFeedbackWindow) visualFeedbackWindow = [[MBFingerTipWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    return visualFeedbackWindow;
}

**Comment by incanus** [comment]
The usual way to enable the class is to replace your app's `UIWindow` with an `MBFingerTipWindow`; that's it!

**Comment by triannabrannon** [comment]
I added the 2 MBFingerTipWindow files to my project as well as his code above to my appdelegate.m file and it's still not working... is there something else I need todo to get this working? Should I be seeing the tap animations right away?

**Comment by incanus** [comment]
Is a secondary display plugged in or else either the `DEBUG_FINGERTIP_WINDOW` or `alwaysShowTouches` on?
