### ISSUE TITLE
Can it work in a swift project?

### ISSUE THREAD

**Issue by tifroz** [mapbox/Fingertips#21]
In the appDelegate's `didFinishLaunchingWithOptions`, I tried setting the `window` property but no luck (Executing the code below, my app landed on a black screen after the splash and that was it - not sure where to go from there)

```
class AppDelegate: UIResponder, UIApplicationDelegate {

  var window: UIWindow?

  func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
  //...
  window = MBFingerTipWindow(frame:UIScreen.mainScreen().bounds)
  //...
}
```

**Comment by incanus** [comment]
Yep, this has worked in our own Swift projects. Your code looks right. Are you setting up the window right otherwise? Example: 

```swift
window = MBFingerTipWindow(frame: UIScreen.mainScreen().bounds)
window!.rootViewController = UINavigationController(rootViewController: mainViewController!)
window!.makeKeyAndVisible()
```

**Comment by tifroz** [comment]
@incanus Thanks! I am not familiar with the `window` object and I had no idea it needed to be associated with a `rootViewController `, and made `KeyAndVisible()`

This works great, and really makes life easier for producing video tutorials of my app, thank you so much for sharing!

One more question if I may - I know other libraries use private APIs to achieve the same result (touchposé is the one I have in mind in particular). Is Fingertips using private APIs to your knowledge? I so I'd have to remove the code from the release build or risk rejection from the App Store submission

**Comment by incanus** [comment]
> One more question if I may - I know other libraries use private APIs to achieve the same result (touchposé is the one I have in mind in particular). Is Fingertips using private APIs to your knowledge?

No, it's not. We've landed apps in the store with it and I know other folks have as well.

**Comment by incanus** [comment]
https://github.com/mapbox/Fingertips/commit/b8b3988b60c9a7476b84469dec77b088365c4e35

**Comment by mehdi-shiba** [comment]
I tried setting up the window as a MBFingerTipWindow in the AppDelegate, but I keep getting "Use of unresolved identifier 'MBFingerTipWindow'". Am i missing something to make this work in a Swift project?

**Comment by hdinhof1** [comment]
@mehdi-shiba I had the same problem. Try importing. `import Fingertips` did the trick.
`import Fingertips

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {`
