### ISSUE TITLE
[super sendEvent:event]; EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by fotiDim** [mapbox/Fingertips#22]
I am getting occasionally EXC_BAD_ACCESS at MBFingetTipWindow.m, line 258:
        [super sendEvent:event];

**Comment by jjxtra** [comment]
I am also seeing this in my crash logs

**Comment by vrohilla-mindroots** [comment]
how to setup this classes in project. iam also trying to embed your classes but it doesn't working.so please guide how to use your classes in my project.

**Comment by 0xced** [comment]
I suggested to improve the README about the setup of Fingertips in #23, see https://github.com/0xced/fingertips/blob/integration-howto-with-storyboards/README.md

**Comment by 1ec5** [comment]
Closing per @0xced.
