### ISSUE TITLE
Doesn't work with Carthage

### ISSUE THREAD

**Issue by Tableau-David-Potter** [mapbox/Fingertips#26]
We're trying to use this with Carthage and when we execute `carthage update` nothing gets built.  Upon further inspection, it appears that the project file is not brought down.  Any ideas?

**Comment by Tableau-David-Potter** [comment]
I found the problem.  When specifying nothing or 0.0.4 as the version, carthage doesn't build anything.  Once I specified "master", it worked.  Can you push up a new version tag?

**Comment by 1ec5** [comment]
Tagged v0.5.0. Does it work for you now?

**Comment by Tableau-David-Potter** [comment]
Yes, it works now.  Thanks.
