### ISSUE TITLE
Support QuickTime recording

### ISSUE THREAD

**Issue by banaslee** [mapbox/Fingertips#28]
Could you please add support for QuickTime recording?

Apparently it's possible to detect if the phone screen is being recorded using the following technique:
[link](http://stackoverflow.com/a/38737416/1130894)

**Comment by henrykchan** [comment]
Any update on this issue? It seems like QuickTime works periodically.

**Comment by CodeWriter23** [comment]
This works for me:

`- (UIWindow *)window {

	if (!_window) {
		_window = [[MBFingerTipWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
		[(MBFingerTipWindow *)_window setAlwaysShowTouches: flag];
	}
	return _window;
}`

**Comment by OdNairy** [comment]
Thanks for the report. The suggestion was implemented in the [0.6.0 release](https://github.com/mapbox/Fingertips/releases/tag/v0.6.0).

**Comment by OdNairy** [comment]
Demo:

https://github.com/mapbox/Fingertips/assets/735178/256ec508-dc13-4d54-b553-c53573707b2a
