### ISSUE TITLE
AlwaysShowFingertips isn't working

### ISSUE THREAD

**Issue by EmperiorEric** [mapbox/Fingertips#29]
setting `alwaysShowFingerTips` to true doesn't seem to be working. I set it to true immediately after creating the window and never saw any fingertips.

**Comment by chizcake** [comment]
I have the same problem as @EmperiorEric has.
My working project is **iOS 10.3** and **Swift 3.1**

I changed the code to use Fingertips
`window = MBFingerTipWindow(frame: UIScreen.main.bounds)`

but nothing has been changed and even **prefersStatusBarHidden** does not work.
Please check this out.  😵
