### ISSUE TITLE
Not working when connecting to MacBook with lightning cable.

### ISSUE THREAD

**Issue by seonman** [mapbox/Fingertips#30]
Fingertips works well when I project the phone screen to AppleTV using AirPlay.
But when I connect the phone to Mac with Lightning cable, it doesn't work.
I have to set alwaysShowTouches as true, then I can see the fingertips, but it always shows.

Can you fix this?

And, can you add enable/disable API to turn on/off the fingertips even when connected to AirPlay?

Thanks.

**Comment by OdNairy** [comment]
Thanks for the report. The issue was addressed in the [0.6.0 release](https://github.com/mapbox/Fingertips/releases/tag/v0.6.0).
