### ISSUE TITLE
Xcode 8.3.3 warning due to targeting iOS 5.0

### ISSUE THREAD

**Issue by DavidPotter** [mapbox/Fingertips#32]
### Expected behavior
No warnings when building an Xcode project that uses CocoaPods to depend on Fingertips.

### Observed behavior
Xcode displays a "Buildtime" warning on Pods.xcodeproj stating "Update to recommended settings". Clicking on the warning displays a view with an issue in Fingertips: "An iOS Deployment Target earlier than 8.0 is not supported by this version of Xcode. This will update the value for Target 'Fingertips' to '8.0'."

### Steps to reproduce
Add `pod 'Fingertips'` to your Podfile
Run `pod install`
Load your Xcode project and build

### Version
Xcode 8.3.3
Fingertips 0.5.0

**Comment by OdNairy** [comment]
Thanks for the report. The issue was addressed in the [0.6.0 release](https://github.com/mapbox/Fingertips/releases/tag/v0.6.0).
