### ISSUE TITLE
Thanks for this lib. I created a guide to help in the installation process

### ISSUE THREAD

**Issue by djabif** [mapbox/Fingertips#33]
Hey, thanks for this repo! 
I created a [step by step guide to install this on your iOS project.
](https://medium.com/learn-ionic-framework/show-touch-and-gestures-on-my-ios-app-screen-recording-2fca596f7bbe)Hope it helps anyone :)

**Comment by hellogerard** [comment]
Thanks for the guide. It got me on my way.

...If you've installed via Cocoapods, use this as your import statement

```objc
#import <Fingertips/MBFingerTipWindow.h>
```

If you're trying to show taps on a Quicktime recording, add this line to the Obj-C block

```objc
- (MBFingerTipWindow *)window
{
  static MBFingerTipWindow *visualFeedbackWindow = nil;
  if (!visualFeedbackWindow) visualFeedbackWindow = [[MBFingerTipWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
  [(MBFingerTipWindow *)visualFeedbackWindow setAlwaysShowTouches: true]; // Add this line
  return visualFeedbackWindow;
}
```
