### ISSUE TITLE
New warning in Xcode 11.4: Missing switch cases

### ISSUE THREAD

**Issue by ghowen** [mapbox/Fingertips#38]
> /Users/xxxx/Projekte/Apps/xxx/Pods/Fingertips/MBFingerTipWindow.m:217:21: Enumeration values 'UITouchPhaseRegionEntered', 'UITouchPhaseRegionMoved', and 'UITouchPhaseRegionExited' not handled in switch

**Comment by OdNairy** [comment]
Thanks for the report. The issue addressed in the [0.6.0 release](https://github.com/mapbox/Fingertips/releases/tag/v0.6.0).
